### ISSUE TITLE
Using Parameters for Source Directory

### ISSUE THREAD

**Issue by ilushka85** [jenkinsci/azure-app-service-plugin#24]
It seems parameters for source directory are not getting parsed.  Any fix planned for this?

**Comment by ArchangelSDY** [comment]
Will implement this in next release.

**Comment by ilushka85** [comment]
Any bounty we can offer to get this done quickly?

**Comment by ArchangelSDY** [comment]
I will work on a patch in the next a few days. It's a small change and you can also do it by yourself.

Just modify this line
https://github.com/jenkinsci/azure-app-service-plugin/blob/f552cab80f512cc4dcb6c635efecae3fc367c258/src/main/java/com/microsoft/jenkins/appservice/WebAppDeploymentRecorder.java#L187

to something like `commandContext.setSourceDirectory(run.getEnvironment(listener).expand(getSourceDirectory()));`

**Comment by ilushka85** [comment]
Thanks looking forward to it
