### ISSUE TITLE
Context name in WAR Deploy

### ISSUE THREAD

**Issue by Artik0** [jenkinsci/azure-app-service-plugin#35]
Hello,

When deploying a WAR file, it seems to happen that the target dir is the same than the WAR filename. When developing with Maven, the artifact name is myappname-x.y.z.war so the target directory and the context name will vary each time a new version is released (so the URL where the application is available: https://myapp.azurewebsites.net/myappname-x.y.z/). Is there any way we can set the context name (and the target directory) so the URL doesn't change?

We use the declarative pipeline sintax to package and deploy the application.

Thank you!

**Comment by ArchangelSDY** [comment]
Why not add a build step to rename the file?

**Comment by gavinfish** [comment]
Hi @Artik0 ,

Have you solved the problem by renaming the file?

**Comment by Artik0** [comment]
Hi,

Where do you suggest to rename the file? I don't know how to do it in a stylish manner in the pipeline so the only way I can think of doing that is in a Maven goal. And that would break the concept of pipeline (each step does its things without knowing about the other steps). If I rename the file in Maven, I won't be able to archive it in a repository (Nexus or Artifactory) in another step in the pipeline.

IMHO this plugin, to be perfect, should have the ability to deploy any file (WAR or JAR) in the context or path I would need to. What do you think?

Thank you!

**Comment by gavinfish** [comment]
What about adding  a `sh 'mv old-file-name new-file-name'` step before publishing to app service? You can change it back if later steps are relied on the file name.
Your suggestion makes sense. It will simplify one WAR file deployments in some situation. But when you deploy several war files at a time, it would be complex to set path for each file at configuration, right?

**Comment by Artik0** [comment]
Ummh... How do you know `old-file-name` if it has been dinamically generated by the Maven step?

About the multiple war deployments... how often do you do that? Isn't it better to deploy each war at a time?

**Comment by gavinfish** [comment]
`mv myappname*.war myappname.war` should work for your case.

@ArchangelSDY could you please provide the scenario that we need to deploy multiple war files at a time? I think it is needed when a project having several sub projects/modules, right?

**Comment by ArchangelSDY** [comment]
Right. Since Jenkins gives us the ability to select multiple files, I can't find a reason to prohibit user from doing this. For complicated path scenario, users can always adjust folder structure in shell before starting deploy. Just don't want to implement too many path manipulation features in this plugin.

**Comment by gavinfish** [comment]
It seems there are no more questions, closing.
