### ISSUE TITLE
Error with Multibranch Pipeline

### ISSUE THREAD

**Issue by geogeocutcut** [jenkinsci/azure-app-service-plugin#36]
When  I use freestyle projet, the deployement run perfectly.
When I use pipeline projet, it's ok.

`[Pipeline] azureWebAppPublish
Starting Azure Web App Deployment
Cloning repository https://smag-testjenkins.scm.azurewebsites.net:443/smag-testjenkins.git
 > F:\Programs\Git\bin\git.exe init F:\workspace\Labs\Smag.gle.pipeline@2\.azure-deploy # timeout=10
Fetching upstream changes from https://smag-testjenkins.scm.azurewebsites.net:443/smag-testjenkins.git
 > F:\Programs\Git\bin\git.exe --version # timeout=10
using GIT_ASKPASS to set credentials 
 > F:\Programs\Git\bin\git.exe fetch --tags --progress https://smag-testjenkins.scm.azurewebsites.net:443/smag-testjenkins.git +refs/heads/*:refs/remotes/origin/*
 > F:\Programs\Git\bin\git.exe config remote.origin.url https://smag-testjenkins.scm.azurewebsites.net:443/smag-testjenkins.git # timeout=10
 > F:\Programs\Git\bin\git.exe config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
Seen branch in repository origin/master
Seen 1 remote branch
 > F:\Programs\Git\bin\git.exe config core.sparsecheckout # timeout=10
 > F:\Programs\Git\bin\git.exe checkout -f master
 > F:\Programs\Git\bin\git.exe add HelloWorld.sln # timeout=10
...`

But when I use multibranch pipeline, I have an error 
`[Pipeline] azureWebAppPublish
16:00:42 Starting Azure Web App Deployment
16:00:44 Cloning repository https://smag-testjenkins.scm.azurewebsites.net:443/smag-testjenkins.git
16:00:44  > F:\Programs\Git\bin\git.exe init F:\workspace\smag.gle\develop\.azure-deploy # timeout=10
16:00:44 Fetching upstream changes from https://smag-testjenkins.scm.azurewebsites.net:443/smag-testjenkins.git
16:00:44  > F:\Programs\Git\bin\git.exe --version # timeout=10
16:00:44 using GIT_ASKPASS to set credentials 
16:00:44  > F:\Programs\Git\bin\git.exe fetch --tags --progress https://smag-testjenkins.scm.azurewebsites.net:443/smag-testjenkins.git +refs/heads/*:refs/remotes/origin/*
16:01:04  > F:\Programs\Git\bin\git.exe config remote.origin.url https://smag-testjenkins.scm.azurewebsites.net:443/smag-testjenkins.git # timeout=10
16:01:04  > F:\Programs\Git\bin\git.exe config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
16:01:04 Seen branch in repository origin/master
16:01:04 Seen 1 remote branch
16:01:04  > F:\Programs\Git\bin\git.exe config core.sparsecheckout # timeout=10
16:01:04  > F:\Programs\Git\bin\git.exe checkout -f master
16:01:05  > F:\Programs\Git\bin\git.exe add F:/workspace/smag.gle/develop/HelloWorld.sln # timeout=10
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // ws
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] End of Pipeline
[Office365connector] No webhooks to notify
hudson.plugins.git.GitException: Command "F:\Programs\Git\bin\git.exe add F:/workspace/smag.gle/develop/HelloWorld.sln" returned status code 128:
stdout: 
stderr: fatal: F:/workspace/smag.gle/develop/HelloWorld.sln: 'F:/workspace/smag.gle/develop/HelloWorld.sln' is outside repository
...`

It seems the path is absolute when it is relative in previous 
HelloWorld.sln is replaced by F:/workspace/smag.gle/develop/HelloWorld.sln

**Comment by gavinfish** [comment]
Moved to jira https://issues.jenkins-ci.org/browse/JENKINS-55637
